openapi: "3.0.0"
info:
  title: Greeting Service
  version: 1.0.0
paths:
  /whirpool:
    get:
      summary: service-assignment resource 
      description: test service-assignment resource
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
      security: []
